### ISSUE TITLE
CALL sqlite_attach('sakila.db') fails with Error: ?]+V

### ISSUE THREAD

**Issue by epoz** [duckdblabs/sqlite_scanner#5] opened 2022-06-29 14:42 UTC
Following the build instructions in a fresh docker container (debian), from a git checkout of this repository:

```shell
# on git commit 6828858bad186eaa69d965a544c1ccb30cf6ef42

root@248181cf905d:/data/sqlitescanner# ./duckdb/build/release/duckdb
v0.4.1-dev169 cee035630
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D LOAD 'build/release/sqlite_scanner.duckdb_extension';
D CALL sqlite_attach('sakila.db');
Error: ?]+V
```

The Load extension call does not give an error, but the attach does.

**Comment by Mause** [comment] 2022-11-06 09:56
This may be a duplicate of #7, are you able to confirm with the instructions I left in a comment there?

**Closed** 2022-11-07 07:57 UTC
