### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by blackrez** [duckdblabs/sqlite_scanner#3] opened 2022-06-04 19:43 UTC
Hello,

duckdb : 0.3.4
OS : Ubuntu 20.04
CPU : arm64

After building the extensions, I load the extensions and after I encounter this error.

```
D LOAD '../sqlitescanner/build/release/sqlite_scanner.duckdb_extension';

Error: IO Error: File "../sqlitescanner/build/release/sqlite_scanner.duckdb_extension" could not be loaded: ../sqlitescanner/build/release/sqlite_scanner.duckdb_extension: undefined symbol: _ZNK6duckdb17TableFunctionData4CopyEv
```

**Comment by blackrez** [comment] 2022-06-08 07:30
Thanks for the update, I have a new error.

```
D LOAD '/media/psf/nabil/project/sqlitescanner/build/release/sqlite_scanner.duckdb_extension';
Error: IO Error: File "/media/psf/nabil/project/sqlitescanner/build/release/sqlite_scanner.duckdb_extension" could not be loaded: /media/psf/nabil/project/sqlitescanner/build/release/sqlite_scanner.duckdb_extension: undefined symbol: _ZTIN6duckdb23LocalTableFunctionStateE
```

**Comment by hannes** [comment] 2022-06-20 11:08
How are you launching the shell? Please don't put the sqlite file name as a parameter there.

**Comment by blackrez** [comment] 2022-06-20 11:26
I'm launching the shell without parameters, as you can see : 
```
nabil@dev-server:/media/psf/nabil/project/sqlitescanner$ duckdb
v0.0.1-dev0
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D LOAD 'build/release/sqlite_scanner.duckdb_extension';
D CALL sqlite_attach('sakila.db');
Error: IO Error: The file is not a valid DuckDB database file!
D
```

**Comment by blackrez** [comment] 2022-06-20 13:42
And if I put a duckdb db instead of a sqlite3 db, the extensions seems to accept the duckdb db.

```
nabil@dev-server:/media/psf/nabil/project/sqlitescanner$ duckdb gnop.db
v0.0.1-dev0
Enter ".help" for usage hints.
D LOAD 'build/release/sqlite_scanner.duckdb_extension';
D CALL sqlite_attach('sakila.db');
Error: IO Error: The file is not a valid DuckDB database file!
D

nabil@dev-server:/media/psf/nabil/project/sqlitescanner$ ls
bench.sql  build       CMakeLists.txt  duckdb   LICENSE   README.md  sakila-examples.sql  sqlite_scanner.cpp  tpch-create.sqlite
borked.db  chinook.db  decimal.db      gnop.db  Makefile  sakila.db  sqlite               test                tpch-export.duckdb
nabil@dev-server:/media/psf/nabil/project/sqlitescanner$ duckdb
v0.0.1-dev0
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D LOAD 'build/release/sqlite_scanner.duckdb_extension';
D CALL sqlite_attach('gnop.db');
D
```

**Comment by Mause** [comment] 2022-11-06 09:57
Duplicate of #7 I think

**Comment by Mause** [comment] 2022-11-07 16:27
This should now be fixed with the latest DuckDB dev version

**Closed by Mause** 2022-11-07 16:27 UTC
